services:
  - type: web
    name: bet-aki-gerenciamento-mkt
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: docs
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
